In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')

In [9]:
df = pd.read_excel('Play_Golf.xlsx',sheet_name='Data')

In [10]:
df.head()

Day   Outlook Temperature Humidity    Wind Play Golf
0    1     Sunny         Hot     High    Weak        No
1    2     Sunny         Hot     High  Strong        No
2    3  Overcast         Hot     High    Weak       Yes
3    4      Rain        Mild     High    Weak       Yes
4    5      Rain        Cool   Normal    Weak       Yes

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Day          14 non-null     int64 
 1   Outlook      14 non-null     object
 2   Temperature  14 non-null     object
 3   Humidity     14 non-null     object
 4   Wind         14 non-null     object
 5   Play Golf    14 non-null     object
dtypes: int64(1), object(5)
memory usage: 800.0+ bytes


## Xác định X (input) và y (target)

In [19]:
X = df.drop(columns=['Day','Play Golf'])
X.head()

Outlook Temperature Humidity    Wind
0     Sunny         Hot     High    Weak
1     Sunny         Hot     High  Strong
2  Overcast         Hot     High    Weak
3      Rain        Mild     High    Weak
4      Rain        Cool   Normal    Weak

In [20]:
y = df['Play Golf']

**Feature Engineering**

**Sử dụng dummies cho các thuộc tính input**

In [21]:
X_new = pd.get_dummies(data=X)
X_new.head()

Outlook_Overcast  Outlook_Rain  Outlook_Sunny  Temperature_Cool  \
0                 0             0              1                 0   
1                 0             0              1                 0   
2                 1             0              0                 0   
3                 0             1              0                 0   
4                 0             1              0                 1   

   Temperature_Hot  Temperature_Mild  Humidity_High  Humidity_Normal  \
0                1                 0              1                0   
1                1                 0              1                0   
2                1                 0              1                0   
3                0                 1              1                0   
4                0                 0              0                1   

   Wind_Strong  Wind_Weak  
0            0          1  
1            1          0  
2            0          1  
3            0          1  
4            0          1

**Sử dụng LabelEncoder cho thuộc tính target**

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
encoder = LabelEncoder()

In [24]:
y_new = encoder.fit_transform(y)
y_new

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

## Sử dụng BernoulliNB

In [25]:
from sklearn.naive_bayes import BernoulliNB

**Khởi tạo model với BernoulliNB**

In [26]:
model = BernoulliNB()

**Huấn luyện model**

In [27]:
model.fit(X_new,y_new)

BernoulliNB()

**Yêu cầu: Với Outlook = Rain, Temperature = Cool, Humidity = High và Windy = Strong thì Play Golf = ?**

Outlook_Overcast,	Outlook_Rain,	Outlook_Sunny,	Temperature_Cool,	Temperature_Hot,	Temperature_Mild,	Humidity_High,	Humidity_Normal,	Wind_Strong	Wind_Weak

**Tạo tập dữ liệu Test**

In [28]:
X_test = [[0,1,0,1,0,0,1,0,1,0]]

In [29]:
y_pred = model.predict(X_test)
y_pred

array([0])

**Nhận xét:
Model dự đoán với điều kiện thời tiết Rain, cool, High, Strong thì không chơi Golf**

## Sử dụng GaussianNB

In [30]:
from sklearn.naive_bayes import GaussianNB

**Khởi tạo model với GaussianNB**

In [31]:
model2 = GaussianNB()

In [32]:
model2.fit(X_new,y_new)

GaussianNB()

In [33]:
y_pred2 = model2.predict(X_test)
y_pred2

array([0])

**Nhận xét:
Model dự đoán với điều kiện thời tiết Rain, cool, High, Strong thì không chơi Golf**